# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check code

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: include stub submodule to base repo
      run: git submodule update --init
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +ux gradlew
    - name: Build workspace
      run: ./gradlew setupThermos --info
    - name: Build with Gradle
      run: ./gradlew jar --info
